import './globals.css';
import { Navigation } from '../components/Navigations';

export const metadata = {
  title: 'My first app with Next 13',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
